// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8_c65K4K9BWBTQ47u92p0B_44T2ActXs',
    appId: '1:193906345429:web:715e7a0d2ef49184e5e95c',
    messagingSenderId: '193906345429',
    projectId: 'cw-6-860bf',
    authDomain: 'cw-6-860bf.firebaseapp.com',
    storageBucket: 'cw-6-860bf.appspot.com',
    measurementId: 'G-MJ9F6QF9FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD702an8BGXTPo3lrd5krOh1RPwNydpb_I',
    appId: '1:193906345429:android:9d948dcbd2a0915ae5e95c',
    messagingSenderId: '193906345429',
    projectId: 'cw-6-860bf',
    storageBucket: 'cw-6-860bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtyOanYSAX9wxBoZgPCMcBEe7mWRvKbKA',
    appId: '1:193906345429:ios:6fd5f167f32bdc99e5e95c',
    messagingSenderId: '193906345429',
    projectId: 'cw-6-860bf',
    storageBucket: 'cw-6-860bf.appspot.com',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtyOanYSAX9wxBoZgPCMcBEe7mWRvKbKA',
    appId: '1:193906345429:ios:88f1bb0decd26123e5e95c',
    messagingSenderId: '193906345429',
    projectId: 'cw-6-860bf',
    storageBucket: 'cw-6-860bf.appspot.com',
    iosBundleId: 'com.example.cw6.RunnerTests',
  );
}
